#!/bin/sh
case "$1" in
        start)
                echo "Starting bt"
				modprobe hci_uart
				sleep 10
				if test -f /root/bt.conf; then
					nohup /root/btctl.sh &
				fi
				
                ;;
        stop)
                echo "Stopping bt"
                ;;
        *)
                echo "Usage: %0 {start|stop}"
        exit 1
esac

exit 0
