#!/bin/sh
#
#       This script will pull the tool states from the "database" and returns a JSON object with all the tool states.
#
echo "Content-type: application/json"
echo


/root/datactrl list 90
